# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/mirzai/',
                'lib_path': 'mirzai'},
  'syms': {'mirzai.data.loading': {'mirzai.data.loading.load_kssl': ('api/data/loading.html#load_kssl', 'mirzai/data/loading.py')}}}