# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mirzai/',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/mirzai/',
                'lib_path': 'mirzai'},
  'syms': { 'mirzai.core': { 'mirzai.core.foo': ('core.html#foo', 'mirzai/core.py'),
                             'mirzai.core.say_hello': ('core.html#say_hello', 'mirzai/core.py')}}}