# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/10_training.plsr.ipynb (unless otherwise specified).


from __future__ import annotations


__all__ = ['compute_valid_curve']

# Cell
#nbdev_comment from __future__ import annotations

# Python utils
from collections import OrderedDict
from tqdm.auto import tqdm

# mirzai utils
from ..data.loading import load_kssl
from ..data.selection import (select_y, select_tax_order, select_X)
from ..data.transform import (log_transform_y, SNV, TakeDerivative,
                                   DropSpectralRegions, CO2_REGION)

# Data science stack
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.cross_decomposition import PLSRegression
from sklearn.metrics import mean_squared_error

from fastcore.test import *
from fastcore.transform import compose

# Cell
def compute_valid_curve(X:np.ndarray, # Spectra with shape (n_samples, n_wavenumbers)
                        y:np.ndarray, # Target with shape (n_samples)
                        X_names:np.ndarray, # Wavenumbers name with shape (n_wavenumbers)
                        mask:np.ndarray=None, # Mask (e.g for specific Soil Taxonomy Orders) with shape (n_samples)
                        pls_components:list=range(5, 120, 5), # List of PLSR components to try
                        seeds:list=range(20), # List of random seeds to use for multiple train/test splits
                        test_size:float=0.1 # Train/test ratio
                       ):
    "Train the PLSR model on training & evaluate it on the valid set as # pls components increases"
    history = OrderedDict({'pls_components': pls_components,
                           'train_score': [],
                           'valid_score': []})
    for seed in tqdm(seeds):
        if mask is None:
            mask = np.full(len(X), True)
        X_train, X_valid, y_train, y_valid = train_test_split(X[mask, : ], y[mask],
                                                              test_size=test_size,
                                                              random_state=seed)

        train_score = []
        valid_score = []
        for cpts in tqdm(pls_components):
            pipe = Pipeline([('snv', SNV()),
                            ('derivative', TakeDerivative(window_length=11, polyorder=1)),
                            ('dropper', DropSpectralRegions(X_names, regions=CO2_REGION)),
                            ('model', PLSRegression(n_components=cpts))])

            pipe.fit(X_train, y_train)

            train_score.append(mean_squared_error(pipe.predict(X_train), y_train))
            valid_score.append(mean_squared_error(pipe.predict(X_valid), y_valid))

        history['train_score'].append(train_score)
        history['valid_score'].append(valid_score)

    return history