# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05_data.transform.ipynb (unless otherwise specified).


from __future__ import annotations


__all__ = ['log_transform_y']

# Cell
#nbdev_comment from __future__ import annotations
from pathlib import Path
import pickle
import numpy as np
from fastcore.test import *

# Cell
def log_transform_y(data:tuple # (X, y, X_id, depth_order)
                   ):
    """
    Log-10 transform of the target value

    Takes and returns all (X, y, X_id, depth_order) tuple to be able to pipe the function
    """
    X, y, X_id, depth_order = data
    y = np.log10(y)
    return X, y, X_id, depth_order