package:
  name: mirzai
  version: 0.1.2
source:
  sha256: 746d1da8efe66d1758a0e2c9776066b81ff4f17199eae0d071923f9911912a63
  url: https://files.pythonhosted.org/packages/c2/27/8bd81072f40783909fea0a4d6494ec4704f2491241a27aa5136f2528f494/mirzai-0.1.2.tar.gz
about:
  dev_url: https://franckalbinet.github.io
  doc_url: https://franckalbinet.github.io
  home: https://franckalbinet.github.io
  license: Apache Software
  license_family: APACHE
  summary: Prediction of Exchangeable Potassium in Soil through Mid-Infrared and Deep
    Learning paper code
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - franckalbinet
requirements:
  host:
  - pip
  - python
  - packaging
  - numpy
  - fastcore>=1.3.27,<1.5
  - scipy
  - matplotlib>=3.5.1
  - scikit-learn
  - torch
  - torchvision
  - tqdm
  - captum
  run:
  - pip
  - python
  - packaging
  - numpy
  - fastcore>=1.3.27,<1.5
  - scipy
  - matplotlib>=3.5.1
  - scikit-learn
  - torch
  - torchvision
  - tqdm
  - captum
test:
  imports:
  - mirzai
