package:
  name: mirzai
  version: 0.0.3
source:
  sha256: 319c0b766edd16300dad76ffad3f6fca580d494096689a7778e01c877818a478
  url: https://files.pythonhosted.org/packages/cd/c5/912bc5db758c1d8a5ad359159c437b3c6621e1dad5d9125f24f62b58e0e8/mirzai-0.0.3.tar.gz
about:
  dev_url: https://franckalbinet.github.io
  doc_url: https://franckalbinet.github.io
  home: https://franckalbinet.github.io
  license: Apache Software
  license_family: APACHE
  summary: Prediction of Exchangeable Potassium in Soil through Mid-Infrared and Deep
    Learning paper code
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - franckalbinet
requirements:
  host:
  - pip
  - python
  - packaging
  - numpy
  - fastcore>=1.3.27,<1.5
  - scipy
  run:
  - pip
  - python
  - packaging
  - numpy
  - fastcore>=1.3.27,<1.5
  - scipy
test:
  imports:
  - mirzai
